### ISSUE TITLE
Refactor from KeystoneJS to react.js

### ISSUE THREAD

**Issue by Nicholas-Nazario** [Nicholas-Nazario/twitterLens#24]
The web-app is going to switch frameworks from KeystoneJS to react.js. This is being done to make integration of the Twitter API and Alphavantage API easier.

**Comment by Daniel-Peladeau** [comment]
The React App has been created and is now under the twitterlens folder within the GitHub Repository. @Nicholas-Nazario please change the front page of the repository to reflect the move to React. The respective calls to install and start a development server need to be added.

**Comment by Daniel-Peladeau** [comment]
The README.md that is displayed on the front page of the repository has been changed to reflect the move to React. This can be closed since the website has been completely moved over to React at this time.

**Comment by Nicholas-Nazario** [comment]
The front page has been updated, and master branch now reflects react.js refactor
