### ISSUE TITLE
Cross-Origin Request Blocked Error

### ISSUE THREAD

**Issue by MattRiina** [Nicholas-Nazario/twitterLens#26]
Trying to use the Twitter API in the new React framework throws the following error: Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.twitter.com/1.1/search/tweets.json?q=Google&language=en&count=100. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by Daniel-Peladeau** [comment]
I believe this issue with this is because of the CORS support in most web browers. React actually has an npm library called 'axios' that allows for easier calls to APIs to return data. Check out https://github.com/axios/axios for more information because this might solve your problem.
