### ISSUE TITLE
App.js Styling Warning in Console

### ISSUE THREAD

**Issue by Daniel-Peladeau** [Nicholas-Nazario/twitterLens#44]
In the web console, "Warning: Received 'true' for a non-boolean attribute 'jsx'. If you want to write it to the DOM, pass a string instead: jsx="true" or jsx={value.toString()}."

This warning needs to be fixed for Beta release and to clean up the console.

**Comment by Daniel-Peladeau** [comment]
This [GitHub Link](https://github.com/zeit/next.js/issues/3432) could be useful to solve this problem.

**Comment by MattRiina** [comment]
In the end, App.js had no impact anymore on Twitter.js, so the <App> tag was able to replaced with the existing <header> tag and App.js was able to be deleted safely
