### ISSUE TITLE
Setup Stock API Calls

### ISSUE THREAD

**Issue by MattRiina** [Nicholas-Nazario/twitterLens#7]
Setup sample calls to the Stock API using Postman to see what the JSON return body looks like and  what data is available

**Comment by Daniel-Peladeau** [comment]
Using a combination of Postman and Python I was able to setup sample calls to the AlphaVantage Stock API. The JSON return body has been recorded and shared with all group members for further analysis. This issue will be closed but at the next group meeting a decision will be made on the time consideration within the Stock API. Data can be taken from intraday all the way to monthly data so a decision will be made to decide which best suits this project.
