### ISSUE TITLE
Research Candlestick Library

### ISSUE THREAD

**Issue by MattRiina** [Nicholas-Nazario/twitterLens#8]
We will be use Candlestick Graphs to represent the stock data, so we must conduct research on how to use the library

**Comment by emanua** [comment]
I am planning to begin testing using Google charts https://developers.google.com/chart for representing both stock and Twitter data.
They have many different types of graphs in their library that could be useful for our goals. For the stocks specifically, if we do use candlestick charts they will look like this https://developers.google.com/chart/interactive/docs/gallery/candlestickchart.
